name: Checkov
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      security-events: write
      id-token: write
    strategy:
      matrix:
        path:
          - /
          - modules/auth0-action
          - modules/auth0-api
          - modules/auth0-auth-db
          - modules/auth0-auth-google
          - modules/auth0-client
          - modules/auth0-email
          - modules/auth0-org
          - modules/auth0-role
          - modules/auth0-tenant
     
    steps:
    - uses: dasmeta/reusable-actions-workflows/checkov@main
      with:
        fetch-depth: 0
        directory: ${{ matrix.path }}
      continue-on-error: true
