name: Tflint
on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  terraform-validate:
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      id-token: write
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - /
          - modules/auth0-action
          - modules/auth0-api
          - modules/auth0-auth-db
          - modules/auth0-auth-google
          - modules/auth0-client
          - modules/auth0-email
          - modules/auth0-org
          - modules/auth0-role
          - modules/auth0-tenant

    steps:
    - uses: dasmeta/reusable-actions-workflows/tflint@main
      with:
        aws-region: ${{ secrets.AWS_REGION}}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        path: ${{ matrix.path }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
